#pragma once

#include <string>
using namespace std;

enum eObserverMessages {
	NOTIFICATION_PLAYER_HIT,
	NOTIFICATION_PLAYER_HEAL,
	NOTIFICATION_PLAYER_SHOOT,
	NOTIFICATION_POWER_UP,
	NOTIFICATION_ENTER_NEW_FLOOR,
	NOTIFICATION_CLEAR_ROOM,
	NOTIFICATION_ENTER_ROOM,
	NOTIFICATION_ENTER_BOSS_ROOM,
	NOTIFICATION_BOSS_HIT,
	NOTIFICATION_BOSS_KILLED,
	NOTIFICATION_PICK_COIN,
	NOTIFICATION_PICK_ITEM
};

/* interface */
class Observer
{
public:
	virtual void notify(eObserverMessages message, void* publisher = nullptr) = 0;
};